version: '3.9'

services:
  db:
    image: postgres:15
    restart: always
    container_name: globant-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: globant_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: globant-api
    ports:
      - "8000:8000"
    environment:
      DB_HOST: db
      DB_USER: admin
      DB_PASSWORD: admin
      DB_NAME: globant_db
    depends_on:
      - db

volumes:
  pgdata: